apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenuiapplication
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mavenuiapplication
  template:
    metadata:
      name: mavenuiapplication
      labels:
        app: mavenuiapplication
    spec:
      containers:
        - name: mavenuiappcontainer
          image: saiprasad07/loginui
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenuiapplication
  labels:
    app: mavenuiapplication
spec:
  selector:
    app: mavenuiapplication
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
